name: windows-compile
on:
  workflow_dispatch:

jobs:
  compile:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: windows-latest
    strategy:
      matrix:
        version:
          - stable
        arch:
          - i386
          - amd64
    steps:
    - uses: actions/checkout@v1
    - uses: RpxdYTX/install-glfw-deps@v2
    - uses: iffy/install-nim@v4.1.1
      with:
        version: ${{ matrix.version }}
    - name: cli
      continue-on-error: true
      run: |
        nimble install -y
        nim c ./pulsar_cli.nim
    - name: windows_i386
      if: matrix.arch == 'i386'
      run: |
        nim --app:gui c --cpu:i386 -d:release --gc:orc --passL:"-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic" ./pulsar.nim
    - name: windows_i386
      if: matrix.arch == 'amd64'
      run: |
        nim --app:gui c --cpu:amd64 -d:release --gc:orc --passL:"-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic" ./pulsar.nim
    - uses: actions/upload-artifact@v2
      with:
        name: 'artifact_win_${{ matrix.arch }}'
        path: |
          ./
          *.nim
          !**/*.nim
