version       = "2.0.0"
author        = "evil#8098 on discord"
description   = "Addon generator for Minecraft bedrock edition"
license       = "GPL 3.0"

requires "nimraylib_now == 0.13.2"
requires "nimclipboard >= 0.1.2"
requires "zippy"
requires "argparse"
requires "uuids"
requires "nigui"
