name: compile-unix
on:
  workflow_dispatch:

jobs:
  compile:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - stable
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: RpxdYTX/install-glfw-deps@v2
    - uses: iffy/install-nim@v4.1.1
      with:
        version: ${{ matrix.version }}
    - name: cli
      continue-on-error: true
      run: |
        nimble install -y
        nim c ./pulsar_cli.nim
    - name: linux_gui
      if: matrix.os == 'ubuntu-latest'
      run: |
        nim --app:gui c -d:release --gc:orc ./pulsar.nim
        chmod +x ./pulsar
    - name: mac_gui
      if: matrix.os == 'macOS-latest'
      run: |
        nim --app:gui --out:pulsar.app c -d:release --gc:orc ./pulsar.nim
        chmod +x ./pulsar.app
    - uses: actions/upload-artifact@v2
      with:
        name: 'artifact_${{ matrix.os }}'
        path: |
          ./
          *.nim
          !**/*.nim
