name: windows-compile
on:
  workflow_dispatch:

jobs:
  compile:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: windows-latest
    strategy:
      matrix:
        version:
          - devel
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v4.1.1
      with:
        version: ${{ matrix.version }}
    - name: windows
      run: |
        nimble install --depsOnly -y
        nim c pulsar_cli.nim
        nim --app:gui c -d:release --gc:orc -d:useMalloc .\pulsar.nim
        nim c --app:lib --out:./User_templates/python/pulsar_py.pyd --threads:on --tlsEmulation:off --passL:-static pulsar_py.nim
        nim --app:gui c -d:release .\pulsar_min.nim
    - uses: actions/upload-artifact@v2
      with:
        name: 'artifact_win'
        path: |
          ./
          *.nim
          !**/*.nim
