name: windows-compile
on:
  workflow_dispatch:

jobs:
  compile:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
        arch:
          - i386
          - amd64
    steps:
    - uses: actions/checkout@v1
    - uses: RpxdYTX/install-glfw-deps@v2
    - uses: iffy/install-nim@v4.1.1
      with:
        version: ${{ matrix.version }}
    - name: cli
      continue-on-error: true
      run: |
        apt install -y mingw-w64
        nimble install -y
        nim c -d:mingw ./pulsar_cli.nim
    - name: windows
      run: |
        nim --app:gui c --cpu:${{ matrix.arch }} -d:mingw --gc:orc ./pulsar.nim
    - uses: actions/upload-artifact@v2
      with:
        name: 'artifact_win_${{ matrix.arch }}'
        path: |
          ./
          *.nim
          !**/*.nim
